"""
Patent Agent Escalation & Report Generation Service
Generates formal, courtroom-grade audit dossiers for handing off assessments
to a Registered Indian Patent Agent or IPR Advocate.
"""

from typing import Dict, Any, List, Optional
from datetime import datetime
import structlog

logger = structlog.get_logger(__name__)


class EscalationDossierService:
    """
    Assembles comprehensive patent intelligence dossiers with statutory citations,
    confidence metrics, mandatory disclaimers, and red-flag checklists.
    """
    def generate_escalation_report(
        self,
        query: str,
        assessment_answer: str,
        statutory_risk: Dict[str, Any],
        citations: List[Dict[str, Any]],
        confidence_data: Dict[str, Any],
        applicant_name: Optional[str] = "Applicant Confidential",
        jurisdiction: str = "national"
    ) -> Dict[str, Any]:
        """
        Creates an exportable dossier structured for professional patent agent review.
        """
        report_id = f"DOSSIER-{datetime.now().strftime('%Y%m%d%H%M%S')}"
        timestamp = datetime.now().strftime("%d-%B-%Y %H:%M:%S UTC")

        # Risk level synthesis
        avg_risk = sum([v for v in statutory_risk.values() if isinstance(v, (int, float))]) / max(len(statutory_risk), 1)
        risk_label = "CRITICAL" if avg_risk > 70 else "MODERATE" if avg_risk > 40 else "FAVORABLE"

        dossier_markdown = f"""# AYUR-LEX-AI: PATENT AGENT PRE-FILING ESCALATION DOSSIER
**Reference ID:** {report_id} | **Date:** {timestamp}
**Target Jurisdiction:** {jurisdiction.upper()} | **Applicant Status:** {applicant_name}
**DPDP Act 2023 Compliance:** Inspected & PII Redacted | **Overall Statutory Risk:** {risk_label} ({avg_risk:.1f}/100)

---

## 1. INQUIRY / INVENTION SPECIFICATION AUDIT
**Subject Matter:**
> {query}

---

## 2. STATUTORY ADJUDICATION & LEGAL OPINION (IRAC METHODOLOGY)
{assessment_answer}

---

## 3. STATUTORY RISK HEATMAP & OBJECTION MATRIX
| Statutory Provision | Risk Level | Statutory Ground | Recommended Overcoming Action |
| :--- | :--- | :--- | :--- |
| **Section 3(p) — Traditional Knowledge** | {statutory_risk.get('section_3p', 50)}% | TKDL Prior Art Documentation Bar | Restrict claims to non-classical standardized fractions or novel ratios. |
| **Section 3(e) — Mere Admixture** | {statutory_risk.get('section_3e', 50)}% | Lacks proof of synergistic bioactivity | Submit Chou-Talalay combination index study with CI < 1.0. |
| **Section 3(d) — Known Substance** | {statutory_risk.get('section_3d', 30)}% | Therapeutic efficacy enhancement test | Provide comparative in-vivo pharmacological clinical superiority data. |
| **BDA Section 6 — NBA Approval** | {statutory_risk.get('bda_clearance', 90)}% | Mandatory Form III approval prior to grant | File Form III with National Biodiversity Authority immediately. |

---

## 4. VERIFIED STATUTORY AUTHORITIES & OFFICIAL CITATIONS
"""
        for i, c in enumerate(citations, 1):
            source = c.get('source_title', 'Statutory Provision')
            section = c.get('section') or c.get('rule') or 'Official Text'
            url = c.get('official_url', 'https://ipindia.gov.in')
            dossier_markdown += f"{i}. **{source}** — *{section}* [Official Reference: {url}]\n"

        dossier_markdown += f"""
---

## 5. CONFIDENCE METRICS & GROUNDING TELEMETRY
- **Overall Confidence Level:** {confidence_data.get('level', 'HIGH')}
- **Grounding Confidence Score:** {confidence_data.get('score', 0.95) * 100:.1f}%
- **Verification Engine:** Deterministic Indian Statutory Reasoner & Hybrid RAG (Qdrant + BM25)

---

## 6. PRE-FILING CHECKLIST FOR REGISTERED PATENT AGENT
- [ ] **Section 10(4)(d)(ii) Compliance:** Verify if source of biological material is declared on Form 1 and Form 2.
- [ ] **NBA Clearance Status:** Ensure NBA Form III application number is cited in the Complete Specification.
- [ ] **Chou-Talalay Proof:** Confirm that working examples in specification incorporate combination index CI < 1.0 or bioavailability isobolograms.
- [ ] **Negative TKDL Disclaimers:** Insert positive disclaimer excluding classical aqueous extracts documented in First Schedule texts.

---

## 7. STATUTORY LEGAL DISCLAIMER
> **IMPORTANT LEGAL NOTICE:**
> This dossier is generated by **Ayur-Lex-AI: Specialized Indian Patent Law & Ayurvedic IPR Engine** solely for preparatory patent intelligence, research evaluation, and patent agent briefing purposes. It does not constitute formal legal counsel or a guarantee of patent grant by the Controller General of Patents, Designs and Trademarks (CGPDTM). All statutory claim amendments must be finalized by a qualified Registered Indian Patent Agent or IPR Advocate.
"""

        return {
            "dossier_id": report_id,
            "timestamp": timestamp,
            "jurisdiction": jurisdiction,
            "applicant_name": applicant_name,
            "overall_risk_label": risk_label,
            "overall_risk_score": avg_risk,
            "confidence_score": confidence_data.get("score", 0.95),
            "citations_count": len(citations),
            "dossier_markdown": dossier_markdown.strip()
        }


escalation_service = EscalationDossierService()
